package:
  name: OCCDataExchange
  version: "0.4.0"

source:
  git_rev: 0.4.0
  git_url: https://github.com/tpaviot/OCCDataExchange.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pythonocc-core
    - OCCUtils
    - qtpy # generalizes PyQt4, PyQt5, PySide imports
    - pyqt5 # the latest, the greatest

test:
  imports:
    - OCCDataExchange

about:
  home: https://github.com/tpaviot/OCCDataExchange
  license: GPL